### ISSUE TITLE
getCity method does not work.

### ISSUE THREAD

**Issue by teylorfeliz** [victorybiz/geoip-location#1]
Hello,

The getCity method does not work because you are returning $this->this->geoData['city'] instead of $this->geoData['city']:

`public function getCity()
    {
        if (empty($this->geoData['city'])) {
            $this->locate();
        }
        return $this->this->geoData['city'];
    }`

Thank you for your work!

**Comment by victorybiz** [comment]
@teylorfeliz thank you for detecting this, I just fixed it in [v1.0.1](https://github.com/victorybiz/geoip-location/releases/tag/v1.0.1)
