### ISSUE TITLE
Issue with PHP 8.1

### ISSUE THREAD

**Issue by miguelapg** [victorybiz/geoip-location#3]
Hi,

Your code works great with PHP 8.1 but I found an issue.

There is the following problem. Nothing important but you should know it ...

PHP Deprecated:  strtoupper(): Passing null to parameter #1 ($string) of type string is deprecated in [...]\victorybiz\geoip-location\src\WebServices\GeoPluginWebService.php on line 48

I fixed it like that ...

BEFORE:

$continent_name = (isset($continents[strtoupper($data['geoplugin_continentCode'])])) ? $continents[strtoupper($data['geoplugin_continentCode'])] : null;

AFTER:

$continent_name = (isset($continents[$data['geoplugin_continentCode']])) ? $continents[$data['geoplugin_continentCode']] : null;

if (!empty($continent_name))
{
	$continent_name = strtoupper($continent_name);
}

Feel free to fix it as you like.

Best regards,
Mapg

**Comment by victorybiz** [comment]
Thank you for reporting this... This issue has been fixed in [v1.1.10](https://github.com/victorybiz/geoip-location/releases/tag/v1.1.10) release.
