### ISSUE TITLE
dependency issue

### ISSUE THREAD

**Issue by threethousand** [victorybiz/geoip-location#4]
Hi,

Im battling with a few packages and php version incompatibilities on my vps.
my current struggles have me on php 8.0.25. now the problems i had are solved, but now instead geoip-location doest work.

When trying version 1.1.10 & 1.1.9 i get the following:
Composer detected issues in your platform: Your Composer dependencies require a PHP version ">= 8.1.0". You are running 8.0.25

and finally, when i try 1.1.8 i get the following:
Problem 1
    - Root composer.json requires victorybiz/geoip-location 1.1.8 -> satisfiable by victorybiz/geoip-location[v1.1.8].
    - victorybiz/geoip-location v1.1.8 requires ipinfo/ipinfo 2.1.x-dev -> found ipinfo/ipinfo[dev-master, v1.0.0, v1.1.0, v1.1.1, v2.0.0, ..., 2.3.x-dev (alias of dev-master)] but it does not match the constraint.

----------------------
I have tried with --ignore-platform-reqs when updating but with no success.

any help with by much appreciated, im so stuck.

**Comment by victorybiz** [comment]
I think this is not an issue directly with this package. This package works with `php >= 7.2` including  `php 8.0` and `php 8.1` and  I recommend installing this package's latest release.

Steps to troubleshoot this;

1. Uninstall this package, and try to run `composer update` or `composer update -ignore-platform-reqs` on your local server.
2. Then re-install this package and test if working locally.

Do not run `composer update` on the production server, run `composer install --no-dev` instead. Run update on the local server.

Please revert if this works or if the issue persists.

**Comment by threethousand** [comment]
thank you for your quick reply Victory!

it seem the problem with all packages was that some need php8 and some php81 when i run update from the command line.
/usr/bin/php8 composer.phar - update

what is the difference between running **install** and **update**? on the different environments?

**Comment by victorybiz** [comment]
Glad you were able to figure it out.

`composer update` will update your dependencies to the latest as they are specified in the `composer.json` file.


`composer install` will not update anything; it will just install all the dependencies as specified in the `composer.lock` file. 

This is the recommended approach on a production server. It will ensure the version of the packages you have tested on your local server is the same as you are running on the production server.

Also, I recommend you develop locally on the same PHP version as you have on the production server.
